; MAX_ACTION_TYPEÀº 1°³ Áö¸¸ ¿©±â¿¡´Â 0¹øÀÎ Ã¤ÆÃ¿¡ ´ëÇÑ °Í¸¸ ÀÖÀ¸¸é µÈ´Ù Á¦½ºÃÄ´Â DataTable¿¡¼­ ¾ò¾î¿Â´Ù.
; MAX_COMMAND_PART ¿¡ µû¶ó COMMAND_PART(¼ýÀÚ) ¸¦ ´Ã·ÁÁÖ¸é¼­ ÇØ´ç ¸í·É¾î¸¦ ±âÀÔÇØÁØ´Ù.
; Á¦½ºÃÄ´Â °ÔÀÓ»ó¿¡¼­ /ÀÎ»ç µî°ú°°ÀÌ »ç¿ëÇÑ´Ù.

[INFO]
MAX_ACTION_TYPE = 1     ;ÃÖ´ë ¾×¼Ç Å¸ÀÔ. 0 : Ã¤ÆÃ  1 : Á¦½ºÃÄ

[ACTION_TYPE1]          ;Ã¤ÆÃ
MAX_COMMAND = 20        ;ÃÖ´ë COMMAND °¹¼ö

[ACTION_TYPE1_COMMAND1] ;ÆÄÆ¼
MAX_COMMAND_PART = 1    ;ÃÖ´ë COMMAND_PART °¹¼ö
COMMAND_PART1 = "/grupo"

[ACTION_TYPE1_COMMAND2] ;±æµå
MAX_COMMAND_PART = 1    ;ÃÖ´ë COMMAND_PART °¹¼ö
COMMAND_PART1 = "/guilda"

[ACTION_TYPE1_COMMAND3] ;±¹°¡
MAX_COMMAND_PART = 1    ;ÃÖ´ë COMMAND_PART °¹¼ö
COMMAND_PART1 = "nação"

[ACTION_TYPE1_COMMAND4] ;Á¾Á·
MAX_COMMAND_PART = 1    ;ÃÖ´ë COMMAND_PART °¹¼ö
COMMAND_PART1 = "/raça"

[ACTION_TYPE1_COMMAND5] ;ÅõÇ¥
MAX_COMMAND_PART = 1    ;ÃÖ´ë COMMAND_PART °¹¼ö
COMMAND_PART1 = "/voto"

[ACTION_TYPE1_COMMAND6] ;Á·Àå·É
MAX_COMMAND_PART = 1    ;ÃÖ´ë COMMAND_PART °¹¼ö
COMMAND_PART1 = "/ordem"

[ACTION_TYPE1_COMMAND7] ;¸Ê
MAX_COMMAND_PART = 1    ;ÃÖ´ë COMMAND_PART °¹¼ö
COMMAND_PART1 = "/mapa"

[ACTION_TYPE1_COMMAND8] ;Á·Àå
MAX_COMMAND_PART = 1    ;ÃÖ´ë COMMAND_PART °¹¼ö
COMMAND_PART1 = "/arconde"

[ACTION_TYPE1_COMMAND9] ;À§¿ø
MAX_COMMAND_PART = 1    ;ÃÖ´ë COMMAND_PART °¹¼ö
COMMAND_PART1 = "membro"

[ACTION_TYPE1_COMMAND10] ;´ëÇ¥
MAX_COMMAND_PART = 1    ;ÃÖ´ë COMMAND_PART °¹¼ö
COMMAND_PART1 = "/rep"

[ACTION_TYPE1_COMMAND11] ;ÀüÃ¼
MAX_COMMAND_PART = 1    ;ÃÖ´ë COMMAND_PART °¹¼ö
COMMAND_PART1 = "/todos"

[ACTION_TYPE1_COMMAND12] ;°Å·¡
MAX_COMMAND_PART = 2    ;ÃÖ´ë COMMAND_PART °¹¼ö
COMMAND_PART1 = "/vender"
COMMAND_PART2 = "/comprar"

[ACTION_TYPE1_COMMAND13] ;GM±×¸®ÆÃ
MAX_COMMAND_PART = 1    ;ÃÖ´ë COMMAND_PART °¹¼ö
COMMAND_PART1 = "$GM"

[ACTION_TYPE1_COMMAND14] ;GM°øÁö
MAX_COMMAND_PART = 1    ;ÃÖ´ë COMMAND_PART °¹¼ö
COMMAND_PART1 = "$aviso"

[ACTION_TYPE1_COMMAND15] ;Á·Àå±×¸®ÆÃ
MAX_COMMAND_PART = 1    ;ÃÖ´ë COMMAND_PART °¹¼ö
COMMAND_PART1 = "$arconde"

[ACTION_TYPE1_COMMAND16] ;±æµå±×¸®ÆÃ
MAX_COMMAND_PART = 1    ;ÃÖ´ë COMMAND_PART °¹¼ö
COMMAND_PART1 = "$guilda"

[ACTION_TYPE1_COMMAND17] ;¿ø°Å¸® ÆÄÆ¼ ÃÊ´ë
MAX_COMMAND_PART = 1    ;ÃÖ´ë COMMAND_PART °¹¼ö
COMMAND_PART1 = "@grupo"

[ACTION_TYPE1_COMMAND18] ;Á·Àå°­È­ Á¦Àç
MAX_COMMAND_PART = 1    ;ÃÖ´ë COMMAND_PART °¹¼ö
COMMAND_PART1 = "@punir"

[ACTION_TYPE1_COMMAND19] ;±Ó¼Ó¸»
MAX_COMMAND_PART = 1    ;ÃÖ´ë COMMAND_PART °¹¼ö
COMMAND_PART1 = "/"

[ACTION_TYPE1_COMMAND20] ;ÃÖ±Ù¿¡ ¹ÞÀº ±Ó¸» ´ë»ó¿¡°Ô º¸³¿
MAX_COMMAND_PART = 1    ;ÃÖ´ë COMMAND_PART °¹¼ö
COMMAND_PART1 = "'"